Changed HeroSection design
murtaja1/find_yours pull request #156
Opened 2021-04-20 22:46 UTC by Othmanosx

2021-04-21 07:28 UTC, murtaja1 requested changes

2021-04-21 07:28 UTC, murtaja1 commented on src/components/Dashboard/Post/Post.jsx
>        </div>
![mobile](https://user-images.githubusercontent.com/53900852/115513745-19636e80-a28c-11eb-9c94-5bc92d8cc4e1.png)

2021-04-21 07:30 UTC, murtaja1 requested changes

2021-04-21 07:30 UTC, murtaja1 commented on src/components/HeroSection/style.js
> +import styled from 'styled-components'
![mobile](https://user-images.githubusercontent.com/53900852/115514179-837c1380-a28c-11eb-8c2c-cf850b18f225.png)

2021-04-21 18:41 UTC, Ravyar19 approved these changes

2021-04-22 06:28 UTC, murtaja1 approved these changes

2021-04-22 06:29 UTC, merged