ContactUs page Fixed #24
murtaja1/find_yours pull request #31
Opened 2021-03-24 18:55 UTC by JalalArif

2021-03-25 12:23 UTC, murtaja1 commented on src/App.js
> +			<ContactUs/>
remove <ContactUs/> from app.js

2021-03-25 12:24 UTC, murtaja1 commented on src/components/ContactUs/contactUs.jsx
> +const useStyles = makeStyles((theme) => ({
create a different file for the styling.

2021-03-25 12:26 UTC, murtaja1 requested changes

2021-03-25 12:26 UTC, murtaja1 commented on src/App.js
> +			<ContactUs/>
remove from contactus app.js

2021-03-25 12:54 UTC, maqalaqil commented
@JalalArif please check comments

2021-03-25 13:14 UTC, Othmanosx commented on src/components/ContactUs/contactUs.jsx
> +  return (
Add Navbar component to the page

2021-03-25 13:14 UTC, Othmanosx commented on src/components/ContactUs/contactUs.jsx
> +    </Container>
Add footer component to the page

2021-03-27 12:24 UTC, Othmanosx commented
Resolve App.js conflict

2021-03-27 12:26 UTC, Othmanosx commented on src/App.js
> +			<ContactUs/>
don't add anything in app.js

2021-03-27 12:27 UTC, Othmanosx reviewed
keep app.js blank

2021-03-29 12:40 UTC, ZhinAbubakr requested changes

2021-03-29 12:40 UTC, ZhinAbubakr commented on src/components/ContactUs/contactUs.jsx
> +        <Typography component="h1" variant="h5">
center align the text inside the h4 tag

2021-03-31 08:03 UTC, ZhinAbubakr approved these changes

2021-03-31 08:12 UTC, murtaja1 approved these changes

2021-04-01 13:02 UTC, maqalaqil approved these changes
LGTM

2021-04-01 18:34 UTC, Ravyar19 approved these changes

2021-04-02 05:23 UTC, merged