Post section
murtaja1/find_yours pull request #50
Opened 2021-04-01 19:04 UTC by Ravyar19

2021-04-02 05:28 UTC, murtaja1 approved these changes

2021-04-02 05:31 UTC, murtaja1 requested changes

2021-04-02 05:31 UTC, murtaja1 commented on src/App.js
> +
this div should be a closing tag.

2021-04-02 10:58 UTC, murtaja1 requested changes

2021-04-02 10:58 UTC, murtaja1 commented on src/components/PostsSection/PostsSection.jsx
> +                        {posts.map((data)=>(
add key to the grid.

2021-04-04 12:22 UTC, murtaja1 requested changes

2021-04-04 12:22 UTC, murtaja1 commented on src/App.js
> +
add closing tag for div.

2021-04-04 12:26 UTC, ZhinAbubakr approved these changes

2021-04-04 13:34 UTC, maqalaqil approved these changes
LGTM

2021-04-04 19:36 UTC, murtaja1 approved these changes

2021-04-05 19:03 UTC, merged