Hero section
murtaja1/find_yours pull request #58
Opened 2021-04-05 10:35 UTC by Ravyar19

2021-04-05 16:43 UTC, murtaja1 approved these changes

2021-04-05 18:36 UTC, Othmanosx approved these changes

2021-04-10 17:41 UTC, MuhannedNoman requested changes

2021-04-10 17:41 UTC, MuhannedNoman commented on src/components/HeroSection/HeroSection.jsx
> +            Welcome to FindYours
Any text should be using i18next translation! 
ex: t('Welcome to FindYours')
This way translation will be easier!

2021-04-10 17:41 UTC, MuhannedNoman commented on src/components/HeroSection/HeroSection.jsx
> +			  /> */}
Commented code should be removed! 
Also, try enforcing this using eslint!

2021-04-10 17:42 UTC, MuhannedNoman commented
Hey @Ravyar19 , nice work you did here! I left you some comments check them out and let me know what you think!

2021-04-13 12:32 UTC, maqalaqil approved these changes
LGTM

2021-04-13 14:15 UTC, merged