Submit button routing in HeroSection
murtaja1/find_yours pull request #60
Opened 2021-04-06 12:12 UTC by ZhinAbubakr

2021-04-06 13:42 UTC, Othmanosx approved these changes

2021-04-10 17:53 UTC, MuhannedNoman requested changes
@ZhinAbubakr , fantastic work here! I have left you some comments to make this better. Let me know what you think!

2021-04-10 17:53 UTC, MuhannedNoman commented on src/components/HeroSection/HeroSection.jsx
> +								</Link>
Indentation looks off here can we fix that?
Also, the text should be using i18next for translations!

2021-04-10 17:53 UTC, MuhannedNoman commented on src/containers/Container.jsx
>                      <Route path="/about" component={About} />
Paths should be in a file called `routes.js` and exported like this 

routes.js
```
export const HOME_ROUTE = '/';
export const DASHBOARD_ROUTE = '/dashboard';
export const NOT_FOUND_ROUTE = '/not-found'
```

This way you only import those and avoid silly mistakes like spelling dashboard wrongly on another component or something!

2021-04-12 22:36 UTC, merged