Feat:Mix lost found
murtaja1/find_yours pull request #63
Opened 2021-04-06 16:44 UTC by Ravyar19

2021-04-06 18:13 UTC, murtaja1 approved these changes

2021-04-07 10:34 UTC, ZhinAbubakr approved these changes

2021-04-10 17:59 UTC, MuhannedNoman requested changes
Hey @Ravyar19 thank you for this work! I have left you some comments to consider. Let me know what you think!

2021-04-10 17:59 UTC, MuhannedNoman commented on src/components/Form/Form.jsx
> +  const [type,setType] =useState("")
This looks like a lot of states! Couldn't be this an object?

2021-04-10 17:59 UTC, MuhannedNoman commented on src/components/Form/Form.jsx
>    }
If the state is an object there won't be any need for this many functions to set the state!

2021-04-10 17:59 UTC, MuhannedNoman commented on src/components/Form/Form.jsx
> +              <h4 className={classes.title}>Item</h4>
Any text should be using i18next for translations!

2021-04-10 17:59 UTC, MuhannedNoman commented on src/components/Form/Form.jsx
> +              />
Since this is a form, why there isn't any validation of data here? 
I would suggest using `yup` or `Joi` for this!

2021-04-12 14:31 UTC, merged